FROM python:3.7.11-slim-stretch

RUN apt-get update && apt-get install --no-install-recommends -y \
    libxml2 \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/setup-users-paths.sh /root/scripts/
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/

USER www-data

ARG image_tag=latest
LABEL org.label-schema.vcs-ref=${image_tag}
