FROM php:8.1-fpm-bullseye@sha256:61c90e54f0d801a351c30679cb47215c10fe5f5941bb40169daafaedcbb972cf

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    libfcgi-bin \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh
COPY --chown=elife:elife ping.php /var/www/html/

COPY config/php-7.1-elife.ini ${PHP_INI_DIR}/conf.d/elife.ini
COPY config/php-7.1-elife-fpm.ini ${PHP_INI_DIR}/conf.d/elife-fpm.ini
COPY config/php-ext-opcache.ini ${PHP_INI_DIR}/conf.d/ext-opcache.ini

USER www-data
