FROM php:7.4-cli-buster@sha256:079138b6e6917f76e182c69781fb3d02e64c198116b3e755f56009035a377634

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh

COPY config/php-7.1-elife.ini ${PHP_INI_DIR}/conf.d/elife.ini
COPY config/php-7.1-elife-fpm.ini ${PHP_INI_DIR}/conf.d/elife-fpm.ini
COPY config/php-ext-opcache.ini ${PHP_INI_DIR}/conf.d/ext-opcache.ini

USER www-data
