FROM python:3.6.4-jessie

RUN apt-get update && apt-get install -y netcat-openbsd

ENV LANG=en_US.UTF-8
COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

RUN pip install -U \
    setuptools \
    uwsgi-tools \
    virtualenv

COPY --chown=elife:elife utils/ /srv/bin/

USER www-data
