FROM php:7.4-fpm-bullseye@sha256:89f487558afd63a5d73676e0bad86d030dcd2d3a3ab176f7a6c5af3650522ab7

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    libfcgi-bin \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh
COPY --chown=elife:elife ping.php /var/www/html/

COPY config/php-7.1-elife.ini ${PHP_INI_DIR}/conf.d/elife.ini
COPY config/php-7.1-elife-fpm.ini ${PHP_INI_DIR}/conf.d/elife-fpm.ini
COPY config/php-ext-opcache.ini ${PHP_INI_DIR}/conf.d/ext-opcache.ini

USER www-data
