FROM python:3.8-slim-bullseye

RUN apt-get update -y
RUN apt-get install --no-install-recommends -y \
    libxml2 \
    netcat-openbsd

# remove some large files introduced by 'apt-get update'
# - https://askubuntu.com/questions/179955/var-lib-apt-lists-is-huge
RUN rm -rf /var/lib/apt/lists/*

# further apt* commands after this point may fail unless an apt-get update happens

# --no-cache-dir, do not cache data
# --only-binary, do not use source packages, only binaries/wheels
RUN pip install --upgrade --no-cache-dir --only-binary :all: --no-color pip wheel pipenv

COPY scripts/setup-users-paths.sh /root/scripts/
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/

USER www-data

ARG image_tag=latest

# deprecated, see:
# - https://github.com/opencontainers/image-spec
# - https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.label-schema.vcs-ref=${image_tag}
