FROM php:7.0.29-cli-jessie

RUN docker-php-ext-install \
    opcache

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY scripts/ /root/scripts
COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh

COPY config/php-7.0-elife.ini ${PHP_INI_DIR}/conf.d/elife.ini

USER www-data
