FROM php:7.0.29-fpm-jessie

RUN apt-get update && apt-get install -y \
    libfcgi0ldbl \
    && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install \
    opcache

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh
COPY --chown=elife:elife ping.php /var/www/html/

COPY config/php-7.0-elife.ini ${PHP_INI_DIR}/conf.d/elife.ini

USER www-data
