FROM php:7.0-fpm-jessie
RUN apt-get update && apt-get install -y git-core zip
# TODO: try apt-get clean

COPY scripts/ /root/scripts
RUN /root/scripts/install-composer.sh

RUN useradd -ms /bin/bash -G www-data elife

USER www-data
