#!/bin/bash
set -e

if [ -z "$DEBUG" ]; then
    composer --no-interaction dump-autoload --no-dev --classmap-authoritative
else
    composer --no-interaction dump-autoload
fi
composer run-script post-install-cmd
