#!/bin/bash
set -e

if [ -z "$DEBUG" ]; then
    composer --no-interaction dump-autoload --no-dev --classmap-authoritative
else
    composer --no-interaction dump-autoload
fi
if composer run-script --list | grep post-install-cmd; then
    composer run-script post-install-cmd
fi
