#!/bin/bash
set -e

if [ -z "$DEBUG" ]; then
    exec composer --no-interaction install --no-suggest --no-dev --no-autoloader
else
    exec composer --no-interaction install --no-suggest --no-autoloader
fi
