#!/bin/bash
set -e

port="${1:-80}"
timeout="${2:-60}"
host="${3:-localhost}"

echo "Waiting for someone listening on port $port"
timeout "$timeout" bash -c "while ! echo > /dev/tcp/$host/$port; do sleep 1; done"
echo "Connection was established on port $port"
